version: '3.8'

networks:
  default:

services:

  db:
    image: mongo:latest
    ports:
      - 27017:27017

  nestjs-app:
    container_name: nestjs-app
    build: ./server
    restart: unless-stopped
    ports:
      - 5000:5000
    stdin_open: true
    tty: true
    volumes:
      - ./nestjs-app:/app
      - /app/node_modules
    networks:
      - default

  nextjs-app:
    container_name: nextjs-app
    build:
      context: ./nextjs-app
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - ./nextjs-app:/app
      - /app/node_modules
      - /app/.next
    networks:
      - default